services:
  - type: web
    name: hifi-horizon
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python app/init_db.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DATABASE_URL
        fromDatabase:
          name: hifihorizon
          property: connectionString